export const AppString = {
  NavigationScreens: {},
  screens: {
    auth: {
      login: {
        header: 'Login',
        googleButton: 'Continue With Google',
        orText: 'OR',
        emailOrPhoneLabel: 'Email or Phone Number',
        emailOrPhonePlaceholder: 'Enter Email or Phone Number',
        emailOrPhoneError: 'Please enter a correct Email or Phone number',
        passwordLabel: 'Password',
        passwordPlaceholder: 'Enter Password',
        passwordError: 'Please enter your Password',
        rememberMe: 'Remember me',
        forgotPassword: 'Forgot Password?',
        loginButton: 'Login',
        noAccount: "Don't have an account?",
        signup: 'Sign Up',
        loginSuccess: 'Login successful',
        loginFailed: 'Invalid username or password',
        forgotPasswordNavigation: 'forgotPassword',
        signupNavigation: 'signup',
      },
      signupStep1: {
        header: 'Get started',
        phoneNumberLabel: 'Phone Number',
        phoneNumberPlaceholder: 'Enter Phone Number',
        phoneNumberError: 'Please enter a correct Phone number',
        signupButton: 'Sign Up',
        haveAccount: 'Have an account?',
        loginButton: 'Login Here',
      },
      signupStep2: {
        header: 'Sign Up',
        headerDescription:
          'Please fill in the following details to create your account with RHYDER',
        firstNameLabel: 'First Name*',
        firstNamePlaceholder: 'Enter First Name',
        firstNameError: 'Please enter your First name',
        lastNameLabel: 'Last Name*',
        lastPlaceholder: 'Enter Last Name',
        lastNameError: 'Please enter your Last name',
        phoneLabel: 'Phone*',
        phonePlaceholder: 'Enter Phone Number',
        phoneNumberError:'Please enter a correct Phone number',
        emailLabel: 'Email*',
        emailPlaceholder: 'Enter Email', 
        emailError: 'Please enter your email',
        passwordLabel: 'Password*',
        passwordPlaceholder: 'Enter Password',
        passwordError: 'Please enter your Password',
        confirmationText:
          'By checking this checkbox I confirm I am a woman by gender',
        signUpButton: 'Sign Up',
      },
    },
  },
};
